apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app
spec:
  replicas: 0
  selector:
    matchLabels:
      app: hello-app
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
      - name: hello-app
        image: rafa775/hello-app:adc0b20d6ea96c978be1982939c232bfc577f9b6
        ports:
        - containerPort: 8000